[build]
  publish = "public"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18.20.0"
  NPM_FLAGS = "--production=false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200